; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                           = 12251118-x86_64 MS Windows   
[ DataSettings ]
datatype                      = snNucleotide                 
containsCodingNuc             = False                        
MissingBaseSymbol             = ?                            
IdenticalBaseSymbol           = .                            
GapSymbol                     = -                            
Labelled Sites                = All Sites                    
Labels to Include             =                              
[ ProcessTypes ]
ppInfer                       = true                         
ppNJ                          = true                         
[ AnalysisSettings ]
Analysis                      = NJ Phylogeny Reconstruction  
Scope                         = All Selected Taxa            
Statistical Method            = Neighbor-joining             
Phylogeny Test                = ====================         
Test of Phylogeny             = Bootstrap method             
Bootstrap Replicates          = 500                          
Substitution Model            = ====================         
Substitutions Type            = Nucleotide                   
Model/Method                  = p-distance                   
Substitutions to Include      = d: Transitions + Transversions
Rates and Patterns            = ====================         
Rates among Sites             = Uniform Rates                
Pattern among Lineages        = Same (Homogeneous)           
Data Subset to Use            = ====================         
Gaps/Missing Data             = Pairwise deletion            
System Resource Usage         = ====================         
Number of Threads             = 7                            
Has Time Limit                = False                        
Maximum Execution Time        = -1                           
